/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

package gobley.gradle.uniffi.tasks

import gobley.gradle.tasks.AbstractFileGenerationTask
import org.gradle.api.tasks.CacheableTask

@CacheableTask
abstract class GenerateUniffiProguardRulesTask : AbstractFileGenerationTask() {
    override fun getDesiredOutput() = StringBuilder().apply {
        appendLine("# Generated by the UniFFI plugin of Gobley.")
        appendLine("# Copied from https://github.com/java-native-access/jna/blob/master/www/FrequentlyAskedQuestions.md#jna-on-android.")
        appendLine("-dontwarn java.awt.*")
        appendLine("-keep class com.sun.jna.* { *; }")
        appendLine("-keepclassmembers class * extends com.sun.jna.* { public *; }")
    }.toString()
}
